recipe: default.v1

assistant_id: 20241208-190308-impulsive-nucleus

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    core_fallback_action_name: "action_call_openai"
    core_fallback_threshold: 0.3
    enable_fallback_prediction: True
    rules:
      - rule: Greet the user
        steps:
          - intent: greet
          - action: utter_greet

      - rule: Handle goodbye
        steps:
          - intent: goodbye
          - action: utter_goodbye

      - rule: Handle bot challenge
        steps:
          - intent: bot_challenge
          - action: utter_iamabot

      - rule: Handle fallback with OpenAI
        steps:
          - intent: nlu_fallback
          - action: action_call_openai
